[toolchain]
anchor_version = "0.24.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ride_sharing_program = "8S32UanLjYVkx9sXzcJtUrk1vaVtNdhMx9rMxkguxKqU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8900"
wallet = "~/.config/solana/id.json"



[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/ride-sharing-program.ts"

[test]
startup_wait = 50000  # You can adjust this value based on your system
